name: Sauce Connect Proxy Action
  # You may pin to the exact commit or the version.
  # uses: saucelabs/sauce-connect-action@30a00c798450b4cb1c26cb766f2d9514c7d08386
  uses: saucelabs/sauce-connect-action@v2.0.0
  with:
    # Sauce Labs user name.
    username: gustaf_nk
    # Sauce Labs API Key.
    accessKey: fbda402b-b11e-4513-85f3-893704c3ba69
    # CA certificate bundle to use for verifying REST connections. (default "/usr/local/etc/openssl/cert.pem")
    cainfo: # optional
    # Directory of CA certs to use for verifying REST connections. (default "/etc/ssl/certs")
    capath: # optional
    # Path to YAML config file. Please refer to https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Command+Line+Reference for a sample configuration file.
    configFile: # optional
    # Comma-separated list of domains. Requests whose host matches one of these will be relayed directly through the internet, instead of through the tunnel.
    directDomains: # optional
    # Use specified name server. To specify multiple servers, separate them with comma. Use IP addresses, optionally with a port number, the two separated by a colon. Example: --dns 8.8.8.8,8.8.4.4:53
    dns: # optional
    # Perform checks to detect possible misconfiguration or problems.
    doctor: # optional
    # Comma-separated list of regular expressions. Requests matching one of these will get dropped instantly and will not go through the tunnel.
    fastFailRegexps: # optional
    # Log statistics about HTTP traffic every <seconds>.
    logStats: # optional
    # Rotate logfile after reaching <bytes> size. Disabled by default.
    maxLogsize: # optional
    # The maximum amount of keepalive acks that can be missed before the client will trigger a reconnect. (default 30)
    maxMissedAcks: # optional
    # host:port for the internal web server used to expose client side metrics. (default "localhost:8888")
    metricsAddress: # optional
    # Disable the autodetection of proxy settings.
    noAutodetect: # optional
    # Disable caching in Sauce Connect. All requests will be sent through the tunnel.
    noProxyCaching: # optional
    # Don't remove identified tunnels with the same name, or any other default tunnels if this is a default tunnel. Jobs will be distributed between these tunnels, enabling load balancing and high availability. By default, colliding tunnels will be removed when Sauce Connect is starting up.
    noRemoveCollidingTunnels: # optional
    # Comma-separated list of domains. Requests whose host matches one of these will not be SSL re-encrypted.
    noSSLBumpDomains: # optional
    # Proxy autoconfiguration. Can be an http(s) or local file:// (absolute path only) URI.
    pac: # optional
    # Proxy host and port that Sauce Connect should use to connect to the Sauce Labs cloud.
    proxy: # optional
    # Use the proxy configured with -p for the tunnel connection.
    proxyTunnel: # optional
    # Username and password required to access the proxy configured with -p.
    proxyUserpwd: # optional
    # Advanced feature: Connect to Sauce REST API at alternative URL. Use only if directed to do so by Sauce Labs support. (default "https://saucelabs.com/rest/v1")
    restUrl: # optional
    # Port on which scproxy will be listening.
    scproxyPort: # optional
    # Rate limit reads in scproxy to X bytes per second. This option can be used to adjust local network transfer rate in order not to overload the tunnel connection.
    scproxyReadLimit: # optional
    # Rate limit writes in scproxy to X bytes per second. This option can be used to adjust local network transfer rate in order not to overload the tunnel connection.
    scproxyWriteLimit: # optional
    # Port on which Sauce Connect's Selenium relay will listen for requests. Selenium commands reaching Connect on this port will be relayed to Sauce Labs securely and reliably through Connect's tunnel (default 4445)
    sePort: # optional
    # Let sub-accounts of the tunnel owner use the tunnel if requested.
    sharedTunnel: # optional
    # CA certificate bundle to use for verifying tunnel connections. (default "/usr/local/etc/openssl/cert.pem")
    tunnelCainfo: # optional
    # Directory of CA certs to use for verifying tunnel connections. (default "/etc/ssl/certs")
    tunnelCapath: # optional
    # Specify certificate to use for the tunnel connection, either public or private. Default: private. (default "private")
    tunnelCert: # optional
    # Inverse of '--direct-domains'. Only requests for domains in this list will be sent through the tunnel. Overrides '--direct-domains'.
    tunnelDomains: # optional
    # Don't automatically assign jobs to this tunnel. Jobs will use it only by explicitly providing the right identifier.
    tunnelIdentifier: # optional
    # Enable verbose logging. Can be used up to two times.
    verbose: # optional
    # Version of the saucelabs/sauce-connect docker image.
    scVersion: # optional, default is 4.6.4
    # Do not retry if this amount of minutes has passed since starting.
    retryTimeout: # optional, default is 10
